apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    options:
      prometheus:
        server-url: "http://prometheus-operated.observability:9090"
    metricsStorage:
      type: prometheus
  ingress:
    enabled: true
    hosts:
      - jaeger.localhost
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-nodeport
  namespace: observability
  labels:
    app: jaeger
    component: all-in-one
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: jaeger
    app: jaeger
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      nodePort: 30091
